#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

START=99
STOP=45

start() {
        cd /mnt/sd/src/ 
        twistd --syslog --pidfile /mnt/sd/src/nrs_twistd.pid -y /mnt/sd/src/yun_serial_writer.py
        echo started
        # commands to launch application
}

stop() {
        kill -INT $(cat /mnt/sd/src/nrs_twistd.pid)
        echo stopped
        # commands to kill application
}
